name: CpGmeth
channels:
- bioconda
dependencies:
- python=2.7
- pandas=0.22.0
- numpy=1.14.3
- pysam=0.14.1
- matplotlib
- biopython=1.71
- xlsxwriter=1.0.2
#- __future__
#- tempfile
#- operator
#- itertools
- toolshed>=0.3.9
